config/routes.rb
PhotoTagger::Application.routes.draw do
  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]

  namespace "api", :defaults => { :format => :json } do
    resources :users, :only => [] do
      resources :photos, :only => [:index, :update]
    end

    resources :photos, :only => [:create] do
      resources :photo_taggings, :only => [:index]
    end

    resources :photo_taggings, :only => [:create]
  end

  root :to => "static_pages#root"
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :owner_id, :title, :url

  belongs_to :owner, :class_name => "User"
  has_many :photo_taggings

  has_many :tagged_users, :through => :photo_taggings, :source => :user


  validates :owner_id, :title, :url, :presence => true
end

app/models/photo_tagging.rb
class PhotoTagging < ActiveRecord::Base
  attr_accessible :photo_id, :user_id, :x_pos, :y_pos

  belongs_to :photo
  belongs_to :user

  validates :photo_id, :user_id, :x_pos, :y_pos, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  has_many(
    :photos,
    class_name: 'Photo',
    foreign_key: :owner_id,
    primary_key: :id,
    inverse_of: :owner)

  has_many(
    :photo_taggings,
    class_name: 'PhotoTagging',
    foreign_key: :user_id,
    primary_key: :id)

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/api/photo_taggings_controller.rb
class Api::PhotoTaggingsController < ApplicationController
  before_filter :require_current_user!, :only => [:create]
  before_filter :require_owner_user!, :only => [:create]

  def create
    @photo_tagging = PhotoTagging.new(params[:photo_tagging])
    if @photo_tagging.save
      render :json => @photo_tagging
    else
      render(
        :json => @photo_tagging.errors.full_messages,
        :status => :unprocessable_entity
      )
    end
  end

  def index
    @photo_taggings =
      PhotoTagging.where("photo_id = ?", params[:photo_id])

    render :json => @photo_taggings
  end

  private
  def require_owner_user!
    # TODO: really should give permission error!
    unless current_user.id == Photo.find(params[:photo_tagging][:photo_id]).owner_id
      redirect_to user_url(current_user)
    end
  end
end

app/controllers/api/photos_controller.rb
class Api::PhotosController < ApplicationController
  before_filter :require_current_user!, :only => [:create]

  def create
    @photo = Photo.new(params[:photo])
    @photo.owner_id = current_user.id
    if @photo.save
      render :json => @photo
    else
      render(
        :json => @photo.errors.full_messages,
        :status => :unprocessible_entity
      )
    end
  end

  def index
    @photos = Photo.where("owner_id = ?", params[:user_id])

    respond_to do |format|
      format.html { render :index }
      format.json { render :json => @photos }
    end
  end

  def update
    @photo = Photo.find(params[:id])

    if @photo.update_attributes(params[:photo])
      render :json => @photo
    else
      render(
        :json => @photo.errors.full_messages,
        :status => :unprocessible_entity
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to root_url
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :require_current_user!

  def root
    render :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to root_url
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoTagger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if !current_user.nil? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>

  <script type="application/json" id="bootstrapped_user_json">
    <%= current_user.id.to_json.html_safe %>
  </script>
  <script>
    CURRENT_USER_ID = JSON.parse($("#bootstrapped_user_json").html())
  </script>
<% end %>

<%= yield %>

</body>
</html>

app/views/static_pages/root.html.erb
<div id="content">
</div>

<script>
  PT.initialize();
</script>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>

<script>
  var photos = PT.Photo.fetchByUserId(<%= current_user.id %>, function() {
    console.log("<%= current_user.photos %>");
  })


</script>